[app]
address = "0.0.0.0:9000"

[db]
host = "listmonk-db"
port = 5432
user = "listmonk"
password = "listmonk"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "5m"

[email]
send_batch_size = 100
send_per_second = 25
max_send_errors = 5

[email.smtp]
enabled = true
host = "smtp.hostinger.com"
port = 465
auth_protocol = "login"
username = "help@tranzlo.net"
password = "Cdromlg@8442"
max_conns = 25
tls_type = "ssl"
hello_hostname = "mail.tranzlo.net"
