export interface Country {
  code: string;
  name: string;
  emoji: string;
  phone: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', emoji: '🇦🇫', phone: '93' },
  { code: 'AL', name: 'Albania', emoji: '🇦🇱', phone: '355' },
  { code: 'DZ', name: 'Algeria', emoji: '🇩🇿', phone: '213' },
  { code: 'AS', name: 'American Samoa', emoji: '🇦🇸', phone: '1684' },
  { code: 'AD', name: 'Andorra', emoji: '🇦🇩', phone: '376' },
  { code: 'AO', name: 'Angola', emoji: '🇦🇴', phone: '244' },
  { code: 'AI', name: 'Anguilla', emoji: '🇦🇮', phone: '1264' },
  { code: 'AQ', name: 'Antarctica', emoji: '🇦🇶', phone: '672' },
  { code: 'AG', name: 'Antigua and Barbuda', emoji: '🇦🇬', phone: '1268' },
  { code: 'AR', name: 'Argentina', emoji: '🇦🇷', phone: '54' },
  { code: 'AM', name: 'Armenia', emoji: '🇦🇲', phone: '374' },
  { code: 'AW', name: 'Aruba', emoji: '🇦🇼', phone: '297' },
  { code: 'AU', name: 'Australia', emoji: '🇦🇺', phone: '61' },
  { code: 'AT', name: 'Austria', emoji: '🇦🇹', phone: '43' },
  { code: 'AZ', name: 'Azerbaijan', emoji: '🇦🇿', phone: '994' },
  { code: 'BS', name: 'Bahamas', emoji: '🇧🇸', phone: '1242' },
  { code: 'BH', name: 'Bahrain', emoji: '🇧🇭', phone: '973' },
  { code: 'BD', name: 'Bangladesh', emoji: '🇧🇩', phone: '880' },
  { code: 'BB', name: 'Barbados', emoji: '🇧🇧', phone: '1246' },
  { code: 'BY', name: 'Belarus', emoji: '🇧🇾', phone: '375' },
  { code: 'BE', name: 'Belgium', emoji: '🇧🇪', phone: '32' },
  { code: 'BZ', name: 'Belize', emoji: '🇧🇿', phone: '501' },
  { code: 'BJ', name: 'Benin', emoji: '🇧🇯', phone: '229' },
  { code: 'BM', name: 'Bermuda', emoji: '🇧🇲', phone: '1441' },
  { code: 'BT', name: 'Bhutan', emoji: '🇧🇹', phone: '975' },
  { code: 'BO', name: 'Bolivia', emoji: '🇧🇴', phone: '591' },
  { code: 'BA', name: 'Bosnia and Herzegovina', emoji: '🇧🇦', phone: '387' },
  { code: 'BW', name: 'Botswana', emoji: '🇧🇼', phone: '267' },
  { code: 'BR', name: 'Brazil', emoji: '🇧🇷', phone: '55' },
  { code: 'IO', name: 'British Indian Ocean Territory', emoji: '🇮🇴', phone: '246' },
  { code: 'VG', name: 'British Virgin Islands', emoji: '🇻🇬', phone: '1284' },
  { code: 'BN', name: 'Brunei', emoji: '🇧🇳', phone: '673' },
  { code: 'BG', name: 'Bulgaria', emoji: '🇧🇬', phone: '359' },
  { code: 'BF', name: 'Burkina Faso', emoji: '🇧🇫', phone: '226' },
  { code: 'BI', name: 'Burundi', emoji: '🇧🇮', phone: '257' },
  { code: 'KH', name: 'Cambodia', emoji: '🇰🇭', phone: '855' },
  { code: 'CM', name: 'Cameroon', emoji: '🇨🇲', phone: '237' },
  { code: 'CA', name: 'Canada', emoji: '🇨🇦', phone: '1' },
  { code: 'CV', name: 'Cape Verde', emoji: '🇨🇻', phone: '238' },
  { code: 'KY', name: 'Cayman Islands', emoji: '🇰🇾', phone: '1345' },
  { code: 'CF', name: 'Central African Republic', emoji: '🇨🇫', phone: '236' },
  { code: 'TD', name: 'Chad', emoji: '🇹🇩', phone: '235' },
  { code: 'CL', name: 'Chile', emoji: '🇨🇱', phone: '56' },
  { code: 'CN', name: 'China', emoji: '🇨🇳', phone: '86' },
  { code: 'CX', name: 'Christmas Island', emoji: '🇨🇽', phone: '61' },
  { code: 'CC', name: 'Cocos [Keeling] Islands', emoji: '🇨🇨', phone: '61' },
  { code: 'CO', name: 'Colombia', emoji: '🇨🇴', phone: '57' },
  { code: 'KM', name: 'Comoros', emoji: '🇰🇲', phone: '269' },
  { code: 'CK', name: 'Cook Islands', emoji: '🇨🇰', phone: '682' },
  { code: 'CR', name: 'Costa Rica', emoji: '🇨🇷', phone: '506' },
  { code: 'HR', name: 'Croatia', emoji: '🇭🇷', phone: '385' },
  { code: 'CU', name: 'Cuba', emoji: '🇨🇺', phone: '53' },
  { code: 'CW', name: 'Curacao', emoji: '🇨🇼', phone: '599' },
  { code: 'CY', name: 'Cyprus', emoji: '🇨🇾', phone: '357' },
  { code: 'CZ', name: 'Czech Republic', emoji: '🇨🇿', phone: '420' },
  { code: 'CD', name: 'Democratic Republic of the Congo', emoji: '🇨🇩', phone: '243' },
  { code: 'DK', name: 'Denmark', emoji: '🇩🇰', phone: '45' },
  { code: 'DJ', name: 'Djibouti', emoji: '🇩🇯', phone: '253' },
  { code: 'DM', name: 'Dominica', emoji: '🇩🇲', phone: '1767' },
  { code: 'DO', name: 'Dominican Republic', emoji: '🇩🇴', phone: '1809' },
  { code: 'EC', name: 'Ecuador', emoji: '🇪🇨', phone: '593' },
  { code: 'EG', name: 'Egypt', emoji: '🇪🇬', phone: '20' },
  { code: 'SV', name: 'El Salvador', emoji: '🇸🇻', phone: '503' },
  { code: 'GQ', name: 'Equatorial Guinea', emoji: '🇬🇶', phone: '240' },
  { code: 'ER', name: 'Eritrea', emoji: '🇪🇷', phone: '291' },
  { code: 'EE', name: 'Estonia', emoji: '🇪🇪', phone: '372' },
  { code: 'ET', name: 'Ethiopia', emoji: '🇪🇹', phone: '251' },
  { code: 'FK', name: 'Falkland Islands', emoji: '🇫🇰', phone: '500' },
  { code: 'FO', name: 'Faroe Islands', emoji: '🇫🇴', phone: '298' },
  { code: 'FJ', name: 'Fiji', emoji: '🇫🇯', phone: '679' },
  { code: 'FI', name: 'Finland', emoji: '🇫🇮', phone: '358' },
  { code: 'FR', name: 'France', emoji: '🇫🇷', phone: '33' },
  { code: 'GF', name: 'French Guiana', emoji: '🇬🇫', phone: '594' },
  { code: 'PF', name: 'French Polynesia', emoji: '🇵🇫', phone: '689' },
  { code: 'TF', name: 'French Southern Territories', emoji: '🇹🇫', phone: '262' },
  { code: 'GA', name: 'Gabon', emoji: '🇬🇦', phone: '241' },
  { code: 'GM', name: 'Gambia', emoji: '🇬🇲', phone: '220' },
  { code: 'GE', name: 'Georgia', emoji: '🇬🇪', phone: '995' },
  { code: 'DE', name: 'German', emoji: '🇩🇪', phone: '49' },
  { code: 'GH', name: 'Ghana', emoji: '🇬🇭', phone: '233' },
  { code: 'GI', name: 'Gibraltar', emoji: '🇬🇮', phone: '350' },
  { code: 'GR', name: 'Greece', emoji: '🇬🇷', phone: '30' },
  { code: 'GL', name: 'Greenland', emoji: '🇬🇱', phone: '299' },
  { code: 'GD', name: 'Grenada', emoji: '🇬🇩', phone: '1473' },
  { code: 'GP', name: 'Guadeloupe', emoji: '🇬🇵', phone: '590' },
  { code: 'GU', name: 'Guam', emoji: '🇬🇺', phone: '1671' },
  { code: 'GT', name: 'Guatemala', emoji: '🇬🇹', phone: '502' },
  { code: 'GG', name: 'Guernsey', emoji: '🇬🇬', phone: '44' },
  { code: 'GN', name: 'Guinea', emoji: '🇬🇳', phone: '224' },
  { code: 'GW', name: 'Guinea-Bissau', emoji: '🇬🇼', phone: '245' },
  { code: 'GY', name: 'Guyana', emoji: '🇬🇾', phone: '592' },
  { code: 'HT', name: 'Haiti', emoji: '🇭🇹', phone: '509' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', emoji: '🇭🇲', phone: '672' },
  { code: 'HN', name: 'Honduras', emoji: '🇭🇳', phone: '504' },
  { code: 'HK', name: 'Hong Kong', emoji: '🇭🇰', phone: '852' },
  { code: 'HU', name: 'Hungary', emoji: '🇭🇺', phone: '36' },
  { code: 'IS', name: 'Iceland', emoji: '🇮🇸', phone: '354' },
  { code: 'IN', name: 'India', emoji: '🇮🇳', phone: '91' },
  { code: 'ID', name: 'Indonesia', emoji: '🇮🇩', phone: '62' },
  { code: 'IR', name: 'Iran', emoji: '🇮🇷', phone: '98' },
  { code: 'IQ', name: 'Iraq', emoji: '🇮🇶', phone: '964' },
  { code: 'IE', name: 'Ireland', emoji: '🇮🇪', phone: '353' },
  { code: 'IM', name: 'Isle of Man', emoji: '🇮🇲', phone: '44' },
  { code: 'IL', name: 'Israel', emoji: '🇮🇱', phone: '972' },
  { code: 'IT', name: 'Italy', emoji: '🇮🇹', phone: '39' },
  { code: 'CI', name: 'Ivory Coast', emoji: '🇨🇮', phone: '225' },
  { code: 'JM', name: 'Jamaica', emoji: '🇯🇲', phone: '1876' },
  { code: 'JP', name: 'Japan', emoji: '🇯🇵', phone: '81' },
  { code: 'JE', name: 'Jersey', emoji: '🇯🇪', phone: '44' },
  { code: 'JO', name: 'Jordan', emoji: '🇯🇴', phone: '962' },
  { code: 'KZ', name: 'Kazakhstan', emoji: '🇰🇿', phone: '7' },
  { code: 'KE', name: 'Kenya', emoji: '🇰🇪', phone: '254' },
  { code: 'KI', name: 'Kiribati', emoji: '🇰🇮', phone: '686' },
  { code: 'XK', name: 'Kosovo', emoji: '🇽🇰', phone: '383' },
  { code: 'KW', name: 'Kuwait', emoji: '🇰🇼', phone: '965' },
  { code: 'KG', name: 'Kyrgyzstan', emoji: '🇰🇬', phone: '996' },
  { code: 'LA', name: 'Laos', emoji: '🇱🇦', phone: '856' },
  { code: 'LV', name: 'Latvia', emoji: '🇱🇻', phone: '371' },
  { code: 'LB', name: 'Lebanon', emoji: '🇱🇧', phone: '961' },
  { code: 'LS', name: 'Lesotho', emoji: '🇱🇸', phone: '266' },
  { code: 'LR', name: 'Liberia', emoji: '🇱🇷', phone: '231' },
  { code: 'LY', name: 'Libya', emoji: '🇱🇾', phone: '218' },
  { code: 'LI', name: 'Liechtenstein', emoji: '🇱🇮', phone: '423' },
  { code: 'LT', name: 'Lithuania', emoji: '🇱🇹', phone: '370' },
  { code: 'LU', name: 'Luxembourg', emoji: '🇱🇺', phone: '352' },
  { code: 'MO', name: 'Macao', emoji: '🇲🇴', phone: '853' },
  { code: 'MK', name: 'Macedonia', emoji: '🇲🇰', phone: '389' },
  { code: 'MG', name: 'Madagascar', emoji: '🇲🇬', phone: '261' },
  { code: 'MW', name: 'Malawi', emoji: '🇲🇼', phone: '265' },
  { code: 'MY', name: 'Malaysia', emoji: '🇲🇾', phone: '60' },
  { code: 'MV', name: 'Maldives', emoji: '🇲🇻', phone: '960' },
  { code: 'ML', name: 'Mali', emoji: '🇲🇱', phone: '223' },
  { code: 'MT', name: 'Malta', emoji: '🇲🇹', phone: '356' },
  { code: 'MH', name: 'Marshall Islands', emoji: '🇲🇭', phone: '692' },
  { code: 'MQ', name: 'Martinique', emoji: '🇲🇶', phone: '596' },
  { code: 'MR', name: 'Mauritania', emoji: '🇲🇷', phone: '222' },
  { code: 'MU', name: 'Mauritius', emoji: '🇲🇺', phone: '230' },
  { code: 'YT', name: 'Mayotte', emoji: '🇾🇹', phone: '262' },
  { code: 'MX', name: 'Mexico', emoji: '🇲🇽', phone: '52' },
  { code: 'FM', name: 'Micronesia', emoji: '🇫🇲', phone: '691' },
  { code: 'MD', name: 'Moldova', emoji: '🇲🇩', phone: '373' },
  { code: 'MC', name: 'Monaco', emoji: '🇲🇨', phone: '377' },
  { code: 'MN', name: 'Mongolia', emoji: '🇲🇳', phone: '976' },
  { code: 'ME', name: 'Montenegro', emoji: '🇲🇪', phone: '382' },
  { code: 'MS', name: 'Montserrat', emoji: '🇲🇸', phone: '1664' },
  { code: 'MA', name: 'Morocco', emoji: '🇲🇦', phone: '212' },
  { code: 'MZ', name: 'Mozambique', emoji: '🇲🇿', phone: '258' },
  { code: 'MM', name: 'Myanmar [Burma]', emoji: '🇲🇲', phone: '95' },
  { code: 'NA', name: 'Namibia', emoji: '🇳🇦', phone: '264' },
  { code: 'NR', name: 'Nauru', emoji: '🇳🇷', phone: '674' },
  { code: 'NP', name: 'Nepal', emoji: '🇳🇵', phone: '977' },
  { code: 'NL', name: 'Netherlands', emoji: '🇳🇱', phone: '31' },
  { code: 'NC', name: 'New Caledonia', emoji: '🇳🇨', phone: '687' },
  { code: 'NZ', name: 'New Zealand', emoji: '🇳🇿', phone: '64' },
  { code: 'NI', name: 'Nicaragua', emoji: '🇳🇮', phone: '505' },
  { code: 'NE', name: 'Niger', emoji: '🇳🇪', phone: '227' },
  { code: 'NG', name: 'Nigeria', emoji: '🇳🇬', phone: '234' },
  { code: 'NU', name: 'Niue', emoji: '🇳🇺', phone: '683' },
  { code: 'NF', name: 'Norfolk Island', emoji: '🇳🇫', phone: '672' },
  { code: 'KP', name: 'North Korea', emoji: '🇰🇵', phone: '850' },
  { code: 'MP', name: 'Northern Mariana Islands', emoji: '🇲🇵', phone: '1670' },
  { code: 'NO', name: 'Norway', emoji: '🇳🇴', phone: '47' },
  { code: 'OM', name: 'Oman', emoji: '🇴🇲', phone: '968' },
  { code: 'PK', name: 'Pakistan', emoji: '🇵🇰', phone: '92' },
  { code: 'PW', name: 'Palau', emoji: '🇵🇼', phone: '680' },
  { code: 'PS', name: 'Palestine', emoji: '🇵🇸', phone: '970' },
  { code: 'PA', name: 'Panama', emoji: '🇵🇦', phone: '507' },
  { code: 'PG', name: 'Papua New Guinea', emoji: '🇵🇬', phone: '675' },
  { code: 'PY', name: 'Paraguay', emoji: '🇵🇾', phone: '595' },
  { code: 'PE', name: 'Peru', emoji: '🇵🇪', phone: '51' },
  { code: 'PH', name: 'Philippines', emoji: '🇵🇭', phone: '63' },
  { code: 'PN', name: 'Pitcairn Islands', emoji: '🇵🇳', phone: '64' },
  { code: 'PL', name: 'Poland', emoji: '🇵🇱', phone: '48' },
  { code: 'PT', name: 'Portugal', emoji: '🇵🇹', phone: '351' },
  { code: 'PR', name: 'Puerto Rico', emoji: '🇵🇷', phone: '1787' },
  { code: 'QA', name: 'Qatar', emoji: '🇶🇦', phone: '974' },
  { code: 'RE', name: 'Reunion', emoji: '🇷🇪', phone: '262' },
  { code: 'RO', name: 'Romania', emoji: '🇷🇴', phone: '40' },
  { code: 'RU', name: 'Russia', emoji: '🇷🇺', phone: '7' },
  { code: 'RW', name: 'Rwanda', emoji: '🇷🇼', phone: '250' },
  { code: 'BL', name: 'Saint Barthelemy', emoji: '🇧🇱', phone: '590' },
  { code: 'SH', name: 'Saint Helena', emoji: '🇸🇭', phone: '290' },
  { code: 'KN', name: 'Saint Kitts and Nevis', emoji: '🇰🇳', phone: '1869' },
  { code: 'LC', name: 'Saint Lucia', emoji: '🇱🇨', phone: '1758' },
  { code: 'MF', name: 'Saint Martin', emoji: '🇲🇫', phone: '590' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', emoji: '🇵🇲', phone: '508' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', emoji: '🇻🇨', phone: '1784' },
  { code: 'WS', name: 'Samoa', emoji: '🇼🇸', phone: '685' },
  { code: 'SM', name: 'San Marino', emoji: '🇸🇲', phone: '378' },
  { code: 'ST', name: 'Sao Tome and Principe', emoji: '🇸🇹', phone: '239' },
  { code: 'SA', name: 'Saudi Arabia', emoji: '🇸🇦', phone: '966' },
  { code: 'SN', name: 'Senegal', emoji: '🇸🇳', phone: '221' },
  { code: 'RS', name: 'Serbia', emoji: '🇷🇸', phone: '381' },
  { code: 'SC', name: 'Seychelles', emoji: '🇸🇨', phone: '248' },
  { code: 'SL', name: 'Sierra Leone', emoji: '🇸🇱', phone: '232' },
  { code: 'SG', name: 'Singapore', emoji: '🇸🇬', phone: '65' },
  { code: 'SX', name: 'Sint Maarten', emoji: '🇸🇽', phone: '1721' },
  { code: 'SK', name: 'Slovakia', emoji: '🇸🇰', phone: '421' },
  { code: 'SI', name: 'Slovenia', emoji: '🇸🇮', phone: '386' },
  { code: 'SB', name: 'Solomon Islands', emoji: '🇸🇧', phone: '677' },
  { code: 'SO', name: 'Somalia', emoji: '🇸🇴', phone: '252' },
  { code: 'ZA', name: 'South Africa', emoji: '🇿🇦', phone: '27' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', emoji: '🇬🇸', phone: '500' },
  { code: 'KR', name: 'South Korea', emoji: '🇰🇷', phone: '82' },
  { code: 'SS', name: 'South Sudan', emoji: '🇸🇸', phone: '211' },
  { code: 'ES', name: 'Spain', emoji: '🇪🇸', phone: '34' },
  { code: 'LK', name: 'Sri Lanka', emoji: '🇱🇰', phone: '94' },
  { code: 'SD', name: 'Sudan', emoji: '🇸🇩', phone: '249' },
  { code: 'SR', name: 'Suriname', emoji: '🇸🇷', phone: '597' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', emoji: '🇸🇯', phone: '47' },
  { code: 'SZ', name: 'Swaziland', emoji: '🇸🇿', phone: '268' },
  { code: 'SE', name: 'Sweden', emoji: '🇸🇪', phone: '46' },
  { code: 'CH', name: 'Switzerland', emoji: '🇨🇭', phone: '41' },
  { code: 'SY', name: 'Syria', emoji: '🇸🇾', phone: '963' },
  { code: 'TW', name: 'Taiwan', emoji: '🇹🇼', phone: '886' },
  { code: 'TJ', name: 'Tajikistan', emoji: '🇹🇯', phone: '992' },
  { code: 'TZ', name: 'Tanzania', emoji: '🇹🇿', phone: '255' },
  { code: 'TH', name: 'Thailand', emoji: '🇹🇭', phone: '66' },
  { code: 'TL', name: 'Timor-Leste', emoji: '🇹🇱', phone: '670' },
  { code: 'TG', name: 'Togo', emoji: '🇹🇬', phone: '228' },
  { code: 'TK', name: 'Tokelau', emoji: '🇹🇰', phone: '690' },
  { code: 'TO', name: 'Tonga', emoji: '🇹🇴', phone: '676' },
  { code: 'TT', name: 'Trinidad and Tobago', emoji: '🇹🇹', phone: '1868' },
  { code: 'TN', name: 'Tunisia', emoji: '🇹🇳', phone: '216' },
  { code: 'TR', name: 'Turkey', emoji: '🇹🇷', phone: '90' },
  { code: 'TM', name: 'Turkmenistan', emoji: '🇹🇲', phone: '993' },
  { code: 'TC', name: 'Turks and Caicos Islands', emoji: '🇹🇨', phone: '1649' },
  { code: 'TV', name: 'Tuvalu', emoji: '🇹🇻', phone: '688' },
  { code: 'UG', name: 'Uganda', emoji: '🇺🇬', phone: '256' },
  { code: 'UA', name: 'Ukraine', emoji: '🇺🇦', phone: '380' },
  { code: 'AE', name: 'United Arab Emirates', emoji: '🇦🇪', phone: '971' },
  { code: 'GB', name: 'United Kingdom', emoji: '🇬🇧', phone: '44' },
  { code: 'US', name: 'United States', emoji: '🇺🇸', phone: '1' },
  { code: 'UY', name: 'Uruguay', emoji: '🇺🇾', phone: '598' },
  { code: 'UZ', name: 'Uzbekistan', emoji: '🇺🇿', phone: '998' },
  { code: 'VU', name: 'Vanuatu', emoji: '🇻🇺', phone: '678' },
  { code: 'VA', name: 'Vatican City', emoji: '🇻🇦', phone: '379' },
  { code: 'VE', name: 'Venezuela', emoji: '🇻🇪', phone: '58' },
  { code: 'VN', name: 'Vietnam', emoji: '🇻🇳', phone: '84' },
  { code: 'WF', name: 'Wallis and Futuna', emoji: '🇼🇫', phone: '681' },
  { code: 'EH', name: 'Western Sahara', emoji: '🇪🇭', phone: '212' },
  { code: 'YE', name: 'Yemen', emoji: '🇾🇪', phone: '967' },
  { code: 'ZM', name: 'Zambia', emoji: '🇿🇲', phone: '260' },
  { code: 'ZW', name: 'Zimbabwe', emoji: '🇿🇼', phone: '263' }
];
