export const PAYPAL_PLANS = {
  TRANSLATOR: {
    STANDARD_MONTHLY: process.env.NEXT_PUBLIC_PAYPAL_PLAN_TRANSLATOR_STD_MONTHLY,
    PLUS_MONTHLY: process.env.NEXT_PUBLIC_PAYPAL_PLAN_TRANSLATOR_PLUS_MONTHLY,
    STANDARD_ANNUAL: process.env.NEXT_PUBLIC_PAYPAL_PLAN_TRANSLATOR_STD_ANNUAL,
    PLUS_ANNUAL: process.env.NEXT_PUBLIC_PAYPAL_PLAN_TRANSLATOR_PLUS_ANNUAL,
  },
  PROFESSIONAL: {
    STANDARD_MONTHLY: process.env.NEXT_PUBLIC_PAYPAL_PLAN_PROFESSIONAL_STD_MONTHLY,
    PLUS_MONTHLY: process.env.NEXT_PUBLIC_PAYPAL_PLAN_PROFESSIONAL_PLUS_MONTHLY,
    STANDARD_ANNUAL: process.env.NEXT_PUBLIC_PAYPAL_PLAN_PROFESSIONAL_STD_ANNUAL,
    PLUS_ANNUAL: process.env.NEXT_PUBLIC_PAYPAL_PLAN_PROFESSIONAL_PLUS_ANNUAL,
  }
};

export const PAYPAL_CONFIG = {
  clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID!,
  webhookId: process.env.PAYPAL_WEBHOOK_ID!,
  mode: 'sandbox', // As specified by user
};
